import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { CounterProvider } from '@/app/context/ContentProvider'

import React from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout(props: {
    children: React.ReactNode
    team: React.ReactNode
    analytics: React.ReactNode
}) {
    return (
        <html lang="ja">
            <body className={inter.className}>
                <CounterProvider>{props.children}</CounterProvider>
                <div>{props.team}</div>
                <div>{props.analytics}</div>
            </body>
        </html>
    )
}
